tutorials.html
Links to the optimal control overview and CRAB example notebooks added
=> Optimal control overview and CRAB

tutorials.html
Added two QuTiP examples to the lectures section, these two lectures show how to  use the new correlation feature with time-dependent Liouvillians and discuss the pulse-wise second-order coherence and two-photon interference in significant detail.
=> Added two QuTiP examples to the lectures section

tutorials.html
Fix for issue reported by @arnelg today
=> example- removed from notebook names in tutorials.hmtl

users.html
=> Two more links for notebooks in users page

tutorials.html, users.html
Removed duplicate entry for Hanschke et al., "Quantum dot single photon sources with ultra-low multi-photon probability".
Added new paper Fischer et al., "Particle emission from open-quantum systems"
Added link to new notebook from PR#54 in qutip-notebooks
=> Add lecture particle emission + new paper + typo

tutorials.html
Added six tutorials about the qutip.piqs module adding a new section in the tutorials page.
=> added piqs tutorials

tutorials.html
The col for piqs should be on the left.
=> Fixed columns

users.html
=> Added new paper citing qutip with notebook link

tutorials.html
- fixed typo
- updated IPython to Jupyter link
=> updated tutorials text introduction

tutorials.html
Add tutorial that exemplifies the use of the new functions `entropy_vn_dicke`, `purity_dicke`, `dicke_blocks`, `dicke_blocks_full`, and `dicke_function_trace`.
=> add piqs tutorial with entropy example

news.html
Update with September news and links to conference websites for material regarding talks and tutorials.
=> add september news: euroscipy and iqis 2019

tutorials.html
Added internal links, added small contents/summary paragraph
=> added internal links to tutorial page

tutorials.html
fixed error where 'Development notebooks' header in summary didn't have a hyperlink
=> fixed minor error with link

docs/latest/apidoc/classes.html, docs/latest/apidoc/functions.html, index.html
changed hyperlink from university of korea image
=> fixed broken source links in API documentation

news.html
Add news about KWoC https://kwoc.kossiitkgp.org/ and Krotov, https://github.com/qucontrol/krotov cc @abhisekupadhyaya @goerz.
=> December 2019 news updates

news.html
Blog links for the first two weeks of our progress updated on the news page
=> Added GSoC updates

tutorials.html
Pairs with qutip/qutip-notebooks#107.
=> Add QobjEvo notebook to index

news.html
=> Update news.html with news about GSoC 2021

index.html, jobs.html, news.html
- Add news on a new Technical Staff Position for QuTiP available at RIKEN, Japan. 
- Add job description in the jobs page
- Added navigator header to homepage 
- Added the job post also on Quantiki and included the link
=> Technical Staff Position for QuTiP available at RIKEN

css/site.css
All animals are equal (but some are more equal than others...)
=> Make the dev photographs all the same size

devs.html
=> Fix name and institution.

news.html
=> Added blogs for GSoC 2021.

tutorials.html
Add new notebooks of qutip-qip and also the tomography notebook of @quantshah
=> Add new qip and tomography notebooks

tutorials.html
Fix #150 
BTW is there a way to preview this? The local copy does not render well on my browser.
=> Remove the redundant closing tags

news.html
Add news on:
- 2022 GSoC Student Blogs + Video presentations
- Quantum Africa Tutorials (Jupyter Book)
- 1M downloads from PyPI and Conda
- QuTiP in the Quantum Open Source Survey
- New tutorials and benchmarks
=> Update News for Q2-Q4 2022

news.html
Not sure if this is the right time to publish this. I think other years this was done later.
=> Added GSoC ideas to news.

qutip-virtual-lab.html
=> Add HTML markup tags to the QuTiP Virtual Lab page.

_includes/sidebar.html
Forgot to update it during the last few releases...
=> Update sidebar title version

_includes/sidebar.html
Forgot to update release date in the sidebar.
=> Fix release date

_includes/sidebar.html, documentation.md, download.md
=> Set latest release as qutip 5.1.0
